"""Theoretical analysis: Why does A_lin predict steering?

Tests the hypothesis: steering works when the steering direction d,
projected through the model's own readout function C = W_U @ LN,
assigns high weight to the target token. That is:

    ΔP ∝ C(d)_target = (W_U @ LN(d))_target

This gives a mechanistic explanation: A_lin measures whether the concept
is aligned with the unembedding's column space. The steering direction
(difference of means) inherits this alignment.

Also measures collateral damage: KL divergence on unrelated prompts
when steering is applied.

Usage:
    python scripts/run_theory_analysis.py --model google/gemma-2-2b --device cuda
    python scripts/run_theory_analysis.py --model Qwen/Qwen2.5-1.5B --device cuda
    python scripts/run_theory_analysis.py --model EleutherAI/pythia-2.8b-deduped --device cuda
"""

import scripts._env  # noqa: F401

import argparse
import json
import gc
import string
import torch
import torch.nn.functional as F
import numpy as np
from pathlib import Path
from collections import Counter
from scipy.stats import spearmanr

from src.data.loader import load_families


def get_token_id(tokenizer, word):
    for text in [" " + word, word]:
        ids = tokenizer.encode(text, add_special_tokens=False)
        if len(ids) == 1:
            return ids[0]
    ids = tokenizer.encode(word, add_special_tokens=False)
    if len(ids) == 2:
        return ids[-1]
    return ids[0] if ids else 0


def is_single_token(tokenizer, word):
    for text in [" " + word, word]:
        ids = tokenizer.encode(text, add_special_tokens=False)
        if len(ids) == 1:
            return True
    return False


# Standard unrelated prompts for collateral damage measurement
COLLATERAL_PROMPTS = [
    "The weather today is", "I went to the store to buy",
    "The population of Tokyo is", "In the year 2000,",
    "The speed of light is", "My favorite hobby is",
    "The largest country in the world is", "Water is composed of",
    "The president of the United States is", "A computer works by",
    "The best way to learn is", "Music can be described as",
    "The purpose of education is", "In mathematics, pi equals",
    "The color of the sky is", "Dogs are known for their",
    "The internet was invented in", "A healthy diet includes",
    "The tallest mountain in the world is", "Electricity is generated by",
    "The human body contains", "Programming languages include",
    "The ocean covers about", "Books are important because",
    "The moon orbits the", "A good leader should",
    "The history of science shows", "Plants need sunlight to",
    "The economy depends on", "Art is a form of",
    "The solar system has", "Coffee is made from",
    "Democracy is a system where", "The brain is responsible for",
    "Cooking requires knowledge of", "Transportation has evolved from",
    "The internet connects", "Medicine has advanced through",
    "Climate change is caused by", "Photography captures",
    "Sleep is important for", "The alphabet has",
    "Mountains are formed by", "Rivers flow toward the",
    "Stars are made of", "Gravity is a force that",
    "Languages evolve over", "The heart pumps",
    "Forests provide", "Technology has changed",
]


def get_model_components(model):
    """Extract final norm, unembed, and layer modules from various architectures."""
    if hasattr(model, "model") and hasattr(model.model, "norm"):
        final_norm = model.model.norm
        layers = model.model.layers
    elif hasattr(model, "gpt_neox"):
        final_norm = model.gpt_neox.final_layer_norm
        layers = model.gpt_neox.layers
    else:
        raise ValueError(f"Unknown architecture: {type(model)}")

    unembed = model.lm_head.weight if hasattr(model, "lm_head") else model.embed_out.weight
    return final_norm, unembed, layers


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--model", default="google/gemma-2-2b")
    parser.add_argument("--device", default="cuda")
    parser.add_argument("--batch-size", type=int, default=16)
    parser.add_argument("--results-dir", default="results")
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()

    model_tag = args.model.split("/")[-1]
    save_dir = Path(args.results_dir) / "theory" / model_tag
    save_dir.mkdir(parents=True, exist_ok=True)

    cache_file = save_dir / "theory_results.json"
    if cache_file.exists() and not args.force:
        print("Loading cached results...")
        with open(cache_file) as f:
            results = json.load(f)
        _print_results(results)
        return

    # Load model
    print(f"Loading model: {args.model}")
    from transformers import AutoModelForCausalLM, AutoTokenizer

    tokenizer = AutoTokenizer.from_pretrained(args.model)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "left"

    model = AutoModelForCausalLM.from_pretrained(
        args.model, torch_dtype=torch.bfloat16,
        attn_implementation="sdpa",
    ).to(args.device)
    model.eval()
    model.config.use_cache = False

    n_layers = model.config.num_hidden_layers
    final_norm, unembed, model_layers = get_model_components(model)

    # Load cross-concept results
    cc_file = Path(args.results_dir) / "cross_concept" / model_tag / "results.json"
    if not cc_file.exists():
        print(f"Error: run cross-concept analysis first ({cc_file})")
        return
    with open(cc_file) as f:
        cc_results = json.load(f)

    # Load families
    families = load_families(n_prompts=2000, include_controlled=True)

    # Get baseline output distribution on collateral prompts
    print("Computing baseline on collateral prompts...")
    with torch.no_grad():
        inp = tokenizer(COLLATERAL_PROMPTS, return_tensors="pt", padding=True,
                        truncation=True, max_length=64).to(args.device)
        # Fix position_ids for left-padded RoPE inputs
        inp["position_ids"] = (inp["attention_mask"].cumsum(-1) - 1).clamp(min=0)
        baseline_out = model(**inp, return_dict=True)
        baseline_logits = baseline_out.logits[:, -1, :].float().cpu()
        baseline_lp = F.log_softmax(baseline_logits, dim=-1)
        del baseline_out

    results = {"model": args.model, "families": {}}

    for fam_name, fam_data in sorted(cc_results["families"].items()):
        if fam_data.get("max_steering_dp") is None or fam_data.get("steering_target") is None:
            continue

        target = fam_data["steering_target"]
        if not is_single_token(tokenizer, target):
            continue

        target_tid = get_token_id(tokenizer, target)
        prompts = families.get(fam_name, [])
        if not prompts:
            continue

        st_prompts = [p for p in prompts if is_single_token(tokenizer, p.correct_answer)]
        if len(st_prompts) < 10:
            continue

        eval_prompts = st_prompts[:500]
        texts = [p.prompt_text for p in eval_prompts]
        target_mask = np.array([p.correct_answer == target for p in eval_prompts])

        if fam_name == "arithmetic":
            other_mask = np.array([p.correct_answer != target and target not in p.prompt_text
                                   for p in eval_prompts])
        else:
            other_mask = ~target_mask

        n_target = int(target_mask.sum())
        n_other = int(other_mask.sum())
        if n_target < 3 or n_other < 10:
            continue

        best_layer = fam_data["best_alin_layer"]

        print(f"\n  {fam_name} (target='{target}', layer=L{best_layer})")

        # Extract hidden states at best layer
        all_h = []
        with torch.no_grad():
            for i in range(0, len(texts), args.batch_size):
                batch = texts[i:i + args.batch_size]
                inp = tokenizer(batch, return_tensors="pt", padding=True,
                                truncation=True, max_length=128).to(args.device)
                # Fix position_ids for left-padded RoPE inputs
                inp["position_ids"] = (inp["attention_mask"].cumsum(-1) - 1).clamp(min=0)
                out = model(**inp, output_hidden_states=True, return_dict=True)
                h = out.hidden_states[best_layer + 1][:, -1, :].cpu().float()
                all_h.append(h)
        H = torch.cat(all_h, dim=0).numpy()

        # Steering direction
        direction = H[target_mask].mean(axis=0) - H[other_mask].mean(axis=0)
        magnitude = float(np.linalg.norm(direction))
        direction_unit = direction / (magnitude + 1e-10)

        # === C(d) ANALYSIS ===
        # Project steering direction through the readout: C(d) = W_U @ LN(d)
        d_tensor = torch.tensor(direction_unit, dtype=torch.bfloat16).unsqueeze(0).to(args.device)
        with torch.no_grad():
            d_normed = final_norm(d_tensor)
            cd = (d_normed.float() @ unembed.T.float()).squeeze(0).cpu()

        cd_target_logit = cd[target_tid].item()
        cd_target_rank = int((cd > cd[target_tid]).sum().item()) + 1
        top5_ids = cd.topk(5).indices.tolist()
        top5_tokens = [(tokenizer.decode([tid]).strip(), cd[tid].item()) for tid in top5_ids]

        # === COLLATERAL DAMAGE ===
        # Steer collateral prompts at the best layer with alpha = ||d||
        alpha = magnitude * 1.0
        perturbation = torch.tensor(
            np.tile(direction_unit, (len(COLLATERAL_PROMPTS), 1)) * alpha,
            dtype=model.dtype,
        )

        steered_logits_list = []
        for i in range(0, len(COLLATERAL_PROMPTS), args.batch_size):
            batch = COLLATERAL_PROMPTS[i:i + args.batch_size]
            batch_pert = perturbation[i:i + len(batch)].to(args.device)

            inp = tokenizer(batch, return_tensors="pt", padding=True,
                            truncation=True, max_length=64).to(args.device)
            # Fix position_ids for left-padded RoPE inputs
            inp["position_ids"] = (inp["attention_mask"].cumsum(-1) - 1).clamp(min=0)
            # With left-padding, last real token is always at the rightmost position
            seq_len = inp["input_ids"].shape[1]
            positions = torch.full((len(batch),), seq_len - 1, device=args.device)

            def make_hook(pert, pos):
                def hook_fn(module, input, output):
                    hs = output[0] if isinstance(output, tuple) else output
                    for j, p in enumerate(pos):
                        hs[j, p] += pert[j]
                    return (hs,) + output[1:] if isinstance(output, tuple) else hs
                return hook_fn

            handle = model_layers[best_layer].register_forward_hook(
                make_hook(batch_pert, positions)
            )
            with torch.no_grad():
                out = model(**inp, return_dict=True)
            handle.remove()

            steered_logits_list.append(out.logits[:, -1, :].float().cpu())

        steered_logits = torch.cat(steered_logits_list, dim=0)
        steered_lp = F.log_softmax(steered_logits, dim=-1)

        # KL divergence: how much does the output change on unrelated prompts?
        kl_per_prompt = F.kl_div(steered_lp, baseline_lp, log_target=True,
                                  reduction="none").sum(dim=-1)
        collateral_kl = float(kl_per_prompt.mean())
        collateral_kl_std = float(kl_per_prompt.std())

        alin = fam_data["best_alin"]
        max_dp = fam_data["max_steering_dp"]

        print(f"    C(d)→target logit: {cd_target_logit:.4f} (rank {cd_target_rank})")
        print(f"    Top C(d) tokens: {', '.join(f'{t}({v:.2f})' for t, v in top5_tokens[:3])}")
        print(f"    Collateral KL: {collateral_kl:.4f} ± {collateral_kl_std:.4f}")
        print(f"    A_lin={alin:.3f}, ΔP={max_dp:+.4f}")

        results["families"][fam_name] = {
            "alin": alin,
            "max_dp": max_dp,
            "best_layer": best_layer,
            "target": target,
            "direction_magnitude": magnitude,
            "cd_target_logit": cd_target_logit,
            "cd_target_rank": cd_target_rank,
            "cd_top5": top5_tokens,
            "collateral_kl_mean": collateral_kl,
            "collateral_kl_std": collateral_kl_std,
        }

        del H, all_h
        torch.cuda.empty_cache()

    # Save
    with open(cache_file, "w") as f:
        json.dump(results, f, indent=2)

    del model
    gc.collect()
    torch.cuda.empty_cache()

    _print_results(results)


def _print_results(results):
    fams = [(f, d) for f, d in results["families"].items()]
    if not fams:
        print("No results")
        return

    print(f"\n{'=' * 90}")
    print(f"THEORETICAL ANALYSIS: {results['model']}")
    print(f"{'=' * 90}")

    # Table
    print(f"\n{'Family':<16} {'A_lin':>6} {'ΔP':>8} {'C(d)→tgt':>10} {'Rank':>6} "
          f"{'‖d‖':>6} {'KL_coll':>8} {'C(d) top tokens':<30}")
    print("-" * 95)
    for f, d in sorted(fams, key=lambda x: x[1]["alin"]):
        top = ", ".join(f"{t}" for t, _ in d["cd_top5"][:3])
        print(f"{f:<16} {d['alin']:>6.3f} {d['max_dp']:>+8.4f} {d['cd_target_logit']:>10.4f} "
              f"{d['cd_target_rank']:>6} {d['direction_magnitude']:>6.1f} "
              f"{d['collateral_kl_mean']:>8.4f} {top:<30}")

    # Correlations
    alins = [d["alin"] for _, d in fams]
    dps = [d["max_dp"] for _, d in fams]
    cd_logits = [d["cd_target_logit"] for _, d in fams]
    cd_ranks = [d["cd_target_rank"] for _, d in fams]
    mags = [d["direction_magnitude"] for _, d in fams]
    kls = [d["collateral_kl_mean"] for _, d in fams]

    print(f"\nCross-concept correlations (n={len(fams)}):")
    for name, vals in [
        ("A_lin", alins),
        ("C(d)_target", cd_logits),
        ("-rank(target)", [-r for r in cd_ranks]),
        ("‖d‖", mags),
        ("C(d)*‖d‖", [c * m for c, m in zip(cd_logits, mags)]),
    ]:
        rho, p = spearmanr(vals, dps)
        print(f"  ρ({name:<16}, ΔP) = {rho:+.3f} (p={p:.4f})")

    print(f"\nCollateral damage correlations:")
    for name, vals in [
        ("A_lin", alins),
        ("‖d‖", mags),
        ("ΔP", dps),
        ("C(d)_target", cd_logits),
    ]:
        rho, p = spearmanr(vals, kls)
        print(f"  ρ({name:<16}, KL_collateral) = {rho:+.3f} (p={p:.4f})")

    # Key question: does high A_lin mean LESS collateral damage per unit steering?
    # Efficiency = ΔP / KL_collateral
    efficiencies = [dp / (kl + 1e-8) for dp, kl in zip(dps, kls)]
    rho_eff, p_eff = spearmanr(alins, efficiencies)
    print(f"\n  ρ(A_lin, ΔP/KL_coll) = {rho_eff:+.3f} (p={p_eff:.4f})")
    print(f"  → Higher A_lin = {'more' if rho_eff > 0 else 'less'} efficient steering")


if __name__ == "__main__":
    main()
